server:
  port: "8081"
  host: "localhost"
  vaults_file_path: "/tmp/vultisigner/plugin/vaults"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: "1"

block_storage:
  type: "s3"
  endpoint: "http://localhost:9000"
  bucket: "vultiplugin" 
  access_key: "minioadmin"
  secret: "minioadmin"
  region: "us-east-1"
  host: "http://localhost:9000"
  force_path_style: true
  disable_ssl: true

relay:
  server: "https://api.vultisig.com/router"

email_server:
  api_key: "your-mandrill-api-key"